AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*.rb'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'public/uploads/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: true
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Style/GuardClause:
  Enabled: false